version: '3.7'

services:
  db:
    image: postgres:15.2
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: test_db
    ports:
      - 5432:5432
    networks:
        - databese-native


networks:
    databese-native:
        driver: bridge